### ISSUE TITLE
Data entry error

### ISSUE THREAD

**Issue by fiammybe** [iForumModule/iforum#4]
I get in many cases that the entry could not be added. Executing the SQL that is shown (look into that, it might be a security risk depending on the user you show it to) results in an error.

The issue is that the field that gives the IP address of the user, is not containing anything. At least ,it should contain ''

**Comment by fiammybe** [comment]
Looks like a problem when the IP address is not an IPv4

**Comment by fiammybe** [comment]
The error message : Could not insert forum post
Insert object error (queryF):INSERT INTO unify__bb_posts (topic_id,forum_id,post_time,poster_ip,poster_name,subject,pid,dohtml,dosmiley,doxcode,dobr,uid,icon,attachsig,approved,post_karma,require_reply) VALUES (5857,49,1548838627,,'','Re: blank page on 1.3.11 softaculous install from scratch',50578,0,1,1,1,1102,'',1,1,0,0)

**Comment by fiammybe** [comment]
you can see that the problem is with the poster_ip value, there is no value at all in the concerned insert statement, making the SQL invalid.

**Comment by skenow** [comment]
Do all/some of those values come from processing the POST? Would setting a default at the head and before sanitizing the values prevent an empty variable?

**Comment by fiammybe** [comment]
That’s what I attempted as a quick fix on production. Only, I couldn’t replicate the problemconsistently, so I cant test if the problem is resolved ☹. The fact that I don’t get the problem doesn’t mean for sure that it isn’t there anymore in my case

Van: Steve
Verzonden: zondag 24 maart 2019 21:04
Aan: iForumModule/iforum
CC: David Janssens; Assign
Onderwerp: Re: [iForumModule/iforum] Data entry error (#4)

Do all/some of those values come from processing the POST? Would setting a default at the head and before sanitizing the values prevent an empty variable?

**Comment by fiammybe** [comment]
When trying to post on the forums when I'm at home gives me the same issue here. I suspect it is because I am using an IP v6 address. After all, the value is not there. I will do another check to see if I caught all the instances where this value is handled. Storing the IP address is perhaps not a very good idea these days, taking into account the different privacy rules.
